application:
  name: PhoneShop

server:
  port: 8080
  servlet:
    context-path: /phone

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3307/phone_service_draft}
    username: root
    password: sa2023
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 7200 # in second
  refreshable-duration: 10800 # in seconds