application:
  name: PhoneShop

server:
  port: 8080
  servlet:
    context-path: /phone

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/phone_service"
    username: root
    password: sa2023
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: true